### ISSUE TITLE
[Question] The future of Stone Catalysts

### ISSUE THREAD

**Issue by NielsPilgaard** [Pxl-8/StoneCatalysts#2]
Hi there! I was wondering, do you plan to update Stone Catalysts beyond 1.15? I hope you don't mind me asking ^^'

**Comment by uberifix** [comment]
I do plan on updating my mods to 1.16+ at some point but unfortunately with everything going on lately I've been burnt out and don't have the energy to do much work. 

I had planned on reworking the catalyst system to allow for more configurability to be able to do things like vanillas new basalt generation and using other modded fluids, and with the rework I wanted to update to 1.16 fresh rather than porting it and making changes so I do not currently have a timeline unfortunately.

**Comment by NielsPilgaard** [comment]
Totally understandable, I'm just glad you plan to update at some point :D thanks for the quick answer.
